export default {
  id: 'sound-pack-1200000000011',
  name: 'NK Cream',
  default: true,
  key_define_type: 'multi',
  includes_numpad: false,
  sound: 'sound.ogg',
  defines: {
    a: 'a.wav',
    b: 'b.wav',
    c: 'c.wav',
    d: 'd.wav',
    e: 'e.wav',
    f: 'f.wav',
    g: 'g.wav',
    h: 'h.wav',
    i: 'i.wav',
    j: 'j.wav',
    k: 'k.wav',
    l: 'l.wav',
    m: 'm.wav',
    n: 'n.wav',
    o: 'o.wav',
    p: 'p.wav',
    q: 'q.wav',
    r: 'r.wav',
    s: 's.wav',
    t: 't.wav',
    u: 'u.wav',
    v: 'v.wav',
    w: 'w.wav',
    x: 'x.wav',
    y: 'y.wav',
    z: 'z.wav',

    A: 'a.wav',
    B: 'b.wav',
    C: 'c.wav',
    D: 'd.wav',
    E: 'e.wav',
    F: 'f.wav',
    G: 'g.wav',
    H: 'h.wav',
    I: 'i.wav',
    J: 'j.wav',
    K: 'k.wav',
    L: 'l.wav',
    M: 'm.wav',
    N: 'n.wav',
    O: 'o.wav',
    P: 'p.wav',
    Q: 'q.wav',
    R: 'r.wav',
    S: 's.wav',
    T: 't.wav',
    U: 'u.wav',
    V: 'v.wav',
    W: 'w.wav',
    X: 'x.wav',
    Y: 'y.wav',
    Z: 'z.wav',

    Backspace: 'backspace.wav',
    Enter: 'enter.wav',
    ' ': 'space.wav',

    Tab: 'tab.wav',
    CapsLock: 'caps-lock.wav',

    Shift: 'shift.wav',
    Control: 'tab.wav',
    Alt: 'tab.wav',
    Escape: 'backspace.wav',

    ArrowUp: 'w.wav',
    ArrowDown: 's.wav',
    ArrowLeft: 'a.wav',
    ArrowRight: 'd.wav',

    1: 'z.wav',
    2: 'x.wav',
    3: 'c.wav',
    4: 'v.wav',
    5: 'b.wav',
    6: 'n.wav',
    7: 'm.wav',
    8: 'l.wav',
    9: '[.wav',
    0: '].wav',
    '-': '[.wav',
    '+': '].wav',

    '!': 'z.wav',
    '@': 'x.wav',
    '#': 'c.wav',
    $: 'v.wav',
    '%': 'b.wav',
    '^': 'n.wav',
    '&': 'm.wav',
    '*': 'l.wav',
    '(': '[.wav',
    ')': '].wav',
    _: '[.wav',
    '=': '].wav',

    // Colons
    ';': '[.wav',
    ':': '[.wav',

    // Quotes
    "'": '].wav',
    '"': '].wav',
    // Commas
    '.': 'l.wav',
    '<': 'l.wav',

    ',': 'k.wav',
    '>': 'k.wav',

    '/': '[.wav',
    '?': '[.wav',
    '\\': 'tab.wav',
    '|': 'tab.wav',
  },
  tags: ['pre-installed'],
}
