export const COLOR_MODE_KEY = 'color_mode'
export const CURRENT_THEME_KEY = 'current_theme'
export const CURRENT_FONT_KEY = 'current_font'
export const USER_FONTS_KEY = 'user_fonts'
export const UI_VOLUME_KEY = 'ui_volume'
export const KB_VOLUME_KEY = 'kb_volume'
export const MUSIC_VOLUME_KEY = 'music_volume'
export const KEYBOARD_SOUND_ATOM = 'keyboard_sound_atom'
